### ISSUE TITLE
[BUG] - `refinery start` leads to gitpython error

### ISSUE THREAD

**Issue by amorisot** [code-kern-ai/refinery#12]
**Describe the bug**
`refinery start` leads to this error, right after pip installing 🥺:
```        
Traceback (most recent call last):
  File "/Users/adrien/miniconda3/bin/refinery", line 5, in <module>
    from refinery.cli import main
  File "/Users/adrien/miniconda3/lib/python3.8/site-packages/refinery/cli.py", line 6, in <module>
    from git import Repo
  File "/Users/adrien/miniconda3/lib/python3.8/site-packages/git/__init__.py", line 6, in <module>
    from repository import Repository, InvalidRepositoryError
ModuleNotFoundError: No module named 'repository'
```

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.4

**Comment by amorisot** [comment]
Yup, I can start from a fresh env. Gimme a few hours :)

**Comment by amorisot** [comment]
Looks like that did it 🎈 

However I'm getting some Docker errors below, and the `UI: http://localhost:4455/app/` link doesn't seem to be working. Is this expected? Very possible that it is! I haven't delved too deeply into the documentation 😊 

```
(base) adrien@Adriens-MacBook-Pro ~ % conda create -n kern     
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/adrien/miniconda3/envs/kern



Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate kern
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) adrien@Adriens-MacBook-Pro ~ % conda activate kern
(kern) adrien@Adriens-MacBook-Pro ~ % pip install kern-refinery
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting kern-refinery
  Using cached kern_refinery-1.0.2-py2.py3-none-any.whl (18 kB)
Collecting wasabi
  Using cached wasabi-0.9.1-py3-none-any.whl (26 kB)
Requirement already satisfied: GitPython in /opt/homebrew/lib/python3.9/site-packages (from kern-refinery) (3.1.27)
Requirement already satisfied: requests in /opt/homebrew/lib/python3.9/site-packages (from kern-refinery) (2.27.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/homebrew/lib/python3.9/site-packages (from GitPython->kern-refinery) (4.0.9)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /opt/homebrew/lib/python3.9/site-packages (from requests->kern-refinery) (1.26.8)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages (from requests->kern-refinery) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from requests->kern-refinery) (2.0.10)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests->kern-refinery) (3.3)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/homebrew/lib/python3.9/site-packages (from gitdb<5,>=4.0.1->GitPython->kern-refinery) (5.0.0)
Installing collected packages: wasabi, kern-refinery
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
  DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Successfully installed kern-refinery-1.0.2 wasabi-0.9.1
(kern) adrien@Adriens-MacBook-Pro ~ % refinery start
ℹ Cloning from code-kern-ai/refinery into repository refinery
./start: line 21: docker: command not found
./start: line 22: docker: command not found
./start: line 23: docker: command not found
./start: line 29: docker-compose: command not found
UI:           http://localhost:4455/app/
Minio:        http://192.168.1.42:7053
MailHog:      http://localhost:4436/
```

**Comment by JWittmeyer** [comment]
great that this fixed this issue. Now for the error messages, it seems you don't have docker installed (or at least it's not recognized by bash). Its used to run the containerized application. Could you check and install [docker desktop](https://www.docker.com/products/docker-desktop/)

**Comment by amorisot** [comment]
sweeeet, that worked 💓 
i had docker desktop downloaded, but hadn't gone through the installation process. thanks for the tip!
