### ISSUE TITLE
[BUG] - Labels that are just numbers can't be imported

### ISSUE THREAD

**Issue by JWittmeyer** [code-kern-ai/refinery#250]
**Describe the bug**
Uploading labels in numerical form results in an error on the import.

**To Reproduce**
1. Go to new project
2. Select a file with labels as numbers (e.g. 1, 2, 3)
3. Upload file

**Expected behavior**
Labels are imported as "1", "2", "3"

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version 1.9.1

**Additional context**
Example file with the issue
[example_numbered labels.zip](https://github.com/code-kern-ai/refinery/files/11383029/example_numbered.labels.1.zip)

Example error log:
```
Traceback (most recent call last):
  File "/app/./api/transfer.py", line 70, in post
    init_file_import(task, project_id, is_global_update)
  File "/app/./api/transfer.py", line 236, in init_file_import
    transfer_manager.import_records_from_file(project_id, task)
  File "/app/./controller/transfer/manager.py", line 69, in import_records_from_file
    import_file(project_id, task)
  File "/app/./controller/transfer/record_transfer_manager.py", line 134, in import_file
    import_records_and_rlas(
  File "/app/./controller/transfer/record_transfer_manager.py", line 66, in import_records_and_rlas
    ) = split_record_data_and_label_data(chunk)
  File "/app/./controller/transfer/record_transfer_manager.py", line 270, in split_record_data_and_label_data
    item.strip() == ""
AttributeError: 'float' object has no attribute 'strip'
```

**Comment by jhoetter** [comment]
`str(item)` should (hopefully) do the trick :)

**Comment by JWittmeyer** [comment]
nope we need slightly more for floats (already have a solution [here](https://github.com/code-kern-ai/refinery-gateway/pull/126) ;) )
